name: Slack Alert
on:
  issues:
    types: [opened]

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'pdegave-kb-test-channel' 
          payload: |
            {
              "text": "🚀 New KB Idea: ${{ github.event.issue.title }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "💡 *New KB idea submitted!*\n📝 *Title:* ${{ github.event.issue.title }}\n👤*Author:* ${{ github.event.issue.user.login }}\n🔗*Link:* ${{ github.event.issue.html_url }}"                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": { "type": "plain_text", "text": "👤 View & Assign" },
                      "url": "${{ github.event.issue.html_url }}"
                    },
                    {
                      "type": "button",
                      "text": { "type": "plain_text", "text": "✅ Close Issue" },
                      "style": "danger",
                      "url": "${{ github.event.issue.html_url }}#issue-comment-box"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
